import type { Metadata } from "next";

import { Syne } from "next/font/google";

import { Header } from "@/widgets/Header/ui/Header";

import "./globals.css";
import { ResizeContainer } from "@/shared/ui/ResizeContainer/ResizeContainer";

const syneSans = Syne({
   variable: "--font-syne",
   subsets: ["latin"],
   weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
   title: "App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang='en'>
         <body className={`bg-black ${syneSans.className}`}>
            <Header />
            <ResizeContainer tag='main'>{children}</ResizeContainer>
         </body>
      </html>
   );
}
